name: Deploy
on:
  push:
    branches: [ main ]   

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: "Build and Test"
        run: |
          dotnet build
          dotnet test
  version:
    needs: test
    runs-on: windows-latest
    outputs: 
      version: ${{ steps.version.outputs.version }}
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Git Version
      id: version
      uses: codacy/git-version@2.7.1
 
      
