name: Deploy
on:
  push:
    branches: [ main ]   

jobs:
  version:
    runs-on: windows-latest
    outputs: 
      version: ${{ env.MAGIC_VERSION }}
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Magic Version
      uses: sinkcup/magic-version@v1.2.0
      env:
        TAG_PREFIX: v # optional
 
      
